#!/bin/bash

source common/clear.sh

source common/functions.sh

# Create your here: http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20
print '  ______    ______    ______   __    __ '
print ' /      \  /      \  /      \ /  |  /  |'
print '/$$$$$$  |/$$$$$$  |/$$$$$$  |$$ | /$$/ '
print '$$ |  $$/ $$ |__$$ |$$ \__$$/ $$ |/$$/  '
print '$$ |      $$    $$ |$$      \ $$  $$<   '
print '$$ |   __ $$$$$$$$ | $$$$$$  |$$$$$  \  '
print '$$ \__/  |$$ |  $$ |/  \__$$ |$$ |$$  \ '
print '$$    $$/ $$ |  $$ |$$    $$/ $$ | $$  |'
print '$$$$$$/  $$/   $$/  $$$$$$/  $$/   $$/  '

if [ "$OS" = "OSX" ]; then
    install  "cask programs" "bash cask/global.sh"
fi
