#!/bin/bash

source common/functions.sh

# Create your here: http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20
print ' _______    ______   ________  ________  ______  __        ________   ______  '
print '/       \  /      \ /        |/        |/      |/  |      /        | /      \ '
print '$$$$$$$  |/$$$$$$  |$$$$$$$$/ $$$$$$$$/ $$$$$$/ $$ |      $$$$$$$$/ /$$$$$$  |'
print '$$ |  $$ |$$ |  $$ |   $$ |   $$ |__      $$ |  $$ |      $$ |__    $$ \__$$/ '
print '$$ |  $$ |$$ |  $$ |   $$ |   $$    |     $$ |  $$ |      $$    |   $$      \ '
print '$$ |  $$ |$$ |  $$ |   $$ |   $$$$$/      $$ |  $$ |      $$$$$/     $$$$$$  |'
print '$$ |__$$ |$$ \__$$ |   $$ |   $$ |       _$$ |_ $$ |_____ $$ |_____ /  \__$$ |'
print '$$    $$/ $$    $$/    $$ |   $$ |      / $$   |$$       |$$       |$$    $$/ '
print '$$$$$$$/   $$$$$$/     $$/    $$/       $$$$$$/ $$$$$$$$/ $$$$$$$$/  $$$$$$/  '

if [[ -d "$HOME/Sites/dotfiles" ]]; then
    print_checking "checking dotfiles directory"
else
    print_checking "cloning dotfiles directory from github"
    git clone git@github.com:emalherbi/dotfiles.git $HOME/Sites/dotfiles
fi

if [ "$OS" = "OSX" ]; then
    print_ln 'OS X Software Updates'
    sh osx/global.sh
else
    print_ln 'Linux Software Updates'
    sh linux/global.sh
fi

print_ln 'Install brew packages'
sh brew/global.sh

print_ln 'Install cask packages'
sh cask/global.sh

print_ln 'Install node packages'
sh node/global.sh

print_ln 'Install ruby packages'
sh ruby/global.sh

print_ln 'Configure dotfiles'
sh common/dotfiles.sh

# TODO:
# installar sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# sudo vim ~/.zshrc
# plugins=(git npm bower brew osx extract z history-substring-search)
